### ISSUE TITLE
broken_options: Add a way to name the arguments to --options

### ISSUE THREAD

**Issue by cvonelm** [tud-zih-energy/nitro#21]
This is somewhat fluff, but with boost::program_options you can name  the arguments to options, which looks like this in --help:

```
x86_adapt options:
  -x [ --x86-adapt-knob ] KNOB          Add x86_adapt knobs as recordings.
                                        Append #accumulated_last for semantics.
```

**Comment by tilsche** [comment]
In accordance with click, we could name this `metavar – how the value is represented in the help page.`
