### ISSUE TITLE
broken_options: function to check if option was given

### ISSUE THREAD

**Issue by cvonelm** [tud-zih-energy/nitro#37]
It would be nice if there was a way to check if an option was given.

example:

```cpp
//test.cpp
parser.option("opt").default_value(42);
options = parser.parse();
std::cout << options.given("opt");
```

```
% ./test
false
% ./test --opt 42
true
```

**Comment by bmario** [comment]
Why isn't the default value enough?

**Comment by cvonelm** [comment]
In my example there is no way to know if opt was manually given or if its just the default value, might be a super rare edge case though.

**Comment by bmario** [comment]
Yes, I understand that, but why do you need to know?

**Comment by cvonelm** [comment]
In lo2s we currently check if both --metric-frequency and --metric-count are given, I could use metric-frequency != [default value] as a check, but if someone calls ./lo2s --metric-frequency [default value] there is no way to know if it was manually or not.

This might be bikeshedding though.

**Comment by bmario** [comment]
So what you actually want is a feature that defines dependencies between options (in this case, a conflict).

**Comment by cvonelm** [comment]
That would be also nice. we currently have a lot of checks in lo2s that are basically just "cant have -a and -b together"
